[package]
name = "desktop-test"
version = "0.1.0"
edition = "2024"

[dependencies]
serialport = "4.7.1"
Mesh = { path = "../libs/Mesh" }
postcard = "1.1.1"
serde = "1.0.219"
chrono = "0.4.40"
csv = "1.3.1"
