[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

[env]
ESP_LOG="info"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]
target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core", "alloc"]
